[package]
name = "launchk"
version = "0.1.1"
authors = ["David Stancu <dstancu@nyu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xpc-sys = { path= "../xpc-sys" }
lazy_static = "1.4.0"
cursive = { version = "0.15.0", features = ["toml"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
plist = "1.1.0"
bitflags = "1.2.1"
notify = "4.0.16"
log = "0.4.14"
env_logger = "0.8.3"
